apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod
  labels:
    app: myapp
    tested: "false"
spec:
  restartPolicy: OnFailure
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'while true; do echo The app is running!; sleep 5; done']