apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels:
    TestLabel: mytestlabel
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            TestLabel: mytestlabel
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
